name: segformer_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy
  - matplotlib
  - pillow
  - requests
  - opencv
  - pip
  - pip:
      - flask
      - transformers
      - uvicorn
      - fastapi
      - aiofiles
      - torch==2.4.0
      - torchvision==0.19.0
      - torchaudio==2.4.0
      - werkzeug
      - tensorflow